# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [68]:
a = 2 + 3 / 5
print(a)

2.6


In [69]:
b = (a + 10.2) - 5 *2.0
print(b)

2.799999999999999


In [70]:
c = a / b + 33.8
print(c)

34.72857142857143


In [71]:
d = a / (b + c)
print(d)

0.0692805481537876


In [72]:
e = d * 2
print(e)

0.1385610963075752


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [73]:
lista_a = [2.0, 3.0, 5.0]
lista_b = [10, 20, 30]
resultado_1 = lista_a + lista_b
print(resultado_1)

[2.0, 3.0, 5.0, 10, 20, 30]


In [74]:
## *2 repete a lista
resultado_2 = lista_a * 2
print(resultado_2)

[2.0, 3.0, 5.0, 2.0, 3.0, 5.0]


In [75]:
resultado_c = lista_a + lista_b
print(resultado_c)

[2.0, 3.0, 5.0, 10, 20, 30]


In [76]:
resultado_d = lista_a / (lista_b * resultado_c)
print(resultado_d)

TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [77]:
lista_1 = [a, b, c, d, e]
lista_1

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752]

In [78]:
lista_2 = [a ** 0.5,
           b ** 0.5,
           c ** 0.5,
           d ** 0.5,
           e ** 0.5]

lista_2

[1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

In [79]:
lista_3 = [lista_1] + [lista_2]
lista_3

[[2.6,
  2.799999999999999,
  34.72857142857143,
  0.0692805481537876,
  0.1385610963075752],
 [1.61245154965971,
  1.6733200530681507,
  5.893095233285427,
  0.263211983302029,
  0.3722379565648501]]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [80]:
lista_duplicada = lista_3 * 2
lista_duplicada

[[2.6,
  2.799999999999999,
  34.72857142857143,
  0.0692805481537876,
  0.1385610963075752],
 [1.61245154965971,
  1.6733200530681507,
  5.893095233285427,
  0.263211983302029,
  0.3722379565648501],
 [2.6,
  2.799999999999999,
  34.72857142857143,
  0.0692805481537876,
  0.1385610963075752],
 [1.61245154965971,
  1.6733200530681507,
  5.893095233285427,
  0.263211983302029,
  0.3722379565648501]]

In [81]:
import numpy as np

In [83]:
array = np.array(lista_duplicada)
array = array.reshape(5, 4)
print(array)


[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [84]:
media_colunas = array.mean(axis=0)
print(media_colunas)

[7.88073291 2.14941306 7.88073291 2.14941306]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [85]:
import numpy as np

In [86]:
array.shape

(5, 4)

In [87]:
novo_array = np.concatenate([array, media_colunas.reshape(1, 4)], axis=0)
print(novo_array)

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]
 [ 7.88073291  2.14941306  7.88073291  2.14941306]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [88]:
array_reshape = novo_array.reshape(-1, 4)
print(array_reshape)

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]
 [ 7.88073291  2.14941306  7.88073291  2.14941306]]


In [89]:
import pandas as pd
df = pd.DataFrame(array_reshape)
df = df.round(3)
print(df)

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [107]:
media_linhas = df.mean(axis=1)
df["media_linha"] = media_linhas
print(df)

        0      1       2      3  media_linha
0   2.600  2.800  34.729  0.069     10.04950
1   0.139  1.612   1.673  5.893      2.32925
2   0.263  0.372   2.600  2.800      1.50875
3  34.729  0.069   0.139  1.612      9.13725
4   1.673  5.893   0.263  0.372      2.05025
5   7.881  2.149   7.881  2.149      5.01500


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [108]:
desc = df.describe()
print(desc)

               0         1          2         3  media_linha
count   6.000000  6.000000   6.000000  6.000000     6.000000
mean    7.880833  2.149167   7.880833  2.149167     5.015000
std    13.455228  2.107787  13.455228  2.107787     3.758615
min     0.139000  0.069000   0.139000  0.069000     1.508750
25%     0.615500  0.682000   0.615500  0.682000     2.120000
50%     2.136500  1.880500   2.136500  1.880500     3.672125
75%     6.560750  2.637250   6.560750  2.637250     8.106688
max    34.729000  5.893000  34.729000  5.893000    10.049500


In [109]:
df_T = df.transpose()[5]
df_T

0              7.881
1              2.149
2              7.881
3              2.149
media_linha    5.015
Name: 5, dtype: float64

In [117]:
ultima_coluna = df.describe().iloc[:, -1]
print(ultima_coluna)

count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: media_linha, dtype: float64


In [116]:
ultima_linha = df.describe().iloc[-1]
print(ultima_linha)

0              34.7290
1               5.8930
2              34.7290
3               5.8930
media_linha    10.0495
Name: max, dtype: float64


## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [118]:
df.columns = ["a", "b", "c", "d", "media_linhas"]
df.index = ["amarelo", "azul", "vermelho", "roxo", "verde", "media_colunas"]
print(df)

                    a      b       c      d  media_linhas
amarelo         2.600  2.800  34.729  0.069      10.04950
azul            0.139  1.612   1.673  5.893       2.32925
vermelho        0.263  0.372   2.600  2.800       1.50875
roxo           34.729  0.069   0.139  1.612       9.13725
verde           1.673  5.893   0.263  0.372       2.05025
media_colunas   7.881  2.149   7.881  2.149       5.01500


In [119]:
media_das_medias = df.iloc[:-1]["media_linhas"].mean()
print(media_das_medias)

5.015000000000001


In [120]:
df.to_csv("arquivoaula7.csv")