# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [49]:
resultado_a= 2.0 + 3.0 / 5.0 == 10
resultado_a

False

In [50]:
resultado_b = (resultado_a + 10.2) - 5.0 * 2.0 <= 2.9
resultado_b

True

In [51]:
resultado_c = 10 <= resultado_a / resultado_b + 33.8 < 100
resultado_c

True

In [52]:
resultado_d = 5 != resultado_a / (resultado_b + resultado_c)
resultado_d

True

In [53]:
resultado_e = 33 == resultado_d * 2
resultado_e

False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [54]:
('a',1,True,'b',0,False) <= ('a',True,1,'b',False,0)

True

In [55]:
['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)

False

In [56]:
['a',1,True,'b',0,False] >= ['a',True,1,'b',False,0]

True

In [57]:
['a',1,True,'b',0,False] < ['a',True,1]

False

In [58]:
['a',1,True,'b',0,False] != 1

True

In [59]:
['a',True,1] <= ['a',True,1] > ['a',1,True,'b',0,False]

False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [60]:
import pandas as pd

In [61]:
df_novo7 = pd.read_csv("arquivoaula7.csv", index_col="Unnamed: 0")
df_novo7 = df_novo7.round(3)

df_novo7

,a,b,c,d,media_linhas
amarelo,2.600,2.800,34.729,0.069,10.050
azul,0.139,1.612,1.673,5.893,2.329
vermelho,0.263,0.372,2.600,2.800,1.509
roxo,34.729,0.069,0.139,1.612,9.137
verde,1.673,5.893,0.263,0.372,2.050
media_colunas,7.881,2.149,7.881,2.149,5.015


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [62]:
import numpy as np

In [63]:
array_novo7 = np.ones(df_novo7.shape)
print(array_novo7)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [64]:
df_array = df_novo7.to_numpy()
iguais = df_array == array_novo7
n_iguais = np.sum(iguais)
print(n_iguais)

0


In [65]:
print(iguais)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [66]:
superior = df_array > array_novo7
n_superior = np.sum(superior)
print(n_superior)

22


In [67]:
print(superior)

[[ True  True  True False  True]
 [False  True  True  True  True]
 [False False  True  True  True]
 [ True False False  True  True]
 [ True  True False False  True]
 [ True  True  True  True  True]]


## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [68]:
igual_ou_inferior = df_array <= array_novo7
n_igual_ou_inferior = np.sum(igual_ou_inferior)
print(n_igual_ou_inferior)

8


In [69]:
print(igual_ou_inferior)

[[False False False  True False]
 [ True False False False False]
 [ True  True False False False]
 [False  True  True False False]
 [False False  True  True False]
 [False False False False False]]


## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [70]:
contidos = (0 < df_array) & (df_array <= 1)
n_contidos = np.sum(contidos)
print(n_contidos)

8


In [71]:
print(contidos)

[[False False False  True False]
 [ True False False False False]
 [ True  True False False False]
 [False  True  True False False]
 [False False  True  True False]
 [False False False False False]]


## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [72]:
media_linhas = df_novo7.mean(axis=1)
lista = list(media_linhas <= 5)
n_linhas = lista.count(True)
print(n_linhas)

3


In [73]:
print(media_linhas)

amarelo          10.0496
azul              2.3292
vermelho          1.5088
roxo              9.1372
verde             2.0502
media_colunas     5.0150
dtype: float64


## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [74]:
media_colunas = df_novo7.mean(axis=0)
lista2 = list(media_colunas > 5)
n_colunas = lista2.count(True)
print(n_colunas)

3


In [75]:
print(media_colunas)

a               7.880833
b               2.149167
c               7.880833
d               2.149167
media_linhas    5.015000
dtype: float64
