# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 

<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

p and q and r and s and t

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [151]:
resultado_p = 2.0 + 3.0 / 5.0 == 10
resultado_p

False

In [152]:
resultado_q = (resultado_p + 10.2) - 5.0 * 2.0 <= 2.9
resultado_q

True

In [153]:
resultado_r = 10 <= resultado_p / resultado_q + 33.8 < 100
resultado_r

True

In [154]:
resultado_s = 5 != resultado_p / (resultado_q + resultado_r)
resultado_s

True

In [155]:
resultado_t = 33 == resultado_s * 2
resultado_t

False

In [156]:
valor = resultado_p and resultado_q and resultado_r and resultado_s and resultado_t
valor

False

In [157]:
valor2 = not (resultado_p and resultado_q and resultado_r and resultado_s and resultado_t)
valor2

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [158]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
p

False

In [159]:
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
q

True

In [160]:
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
r

False

In [161]:
s = ['a',1,True,'b',0,False] > ['a',True,1]
s

True

In [162]:
t = ['a',1,True,'b',0,False] == 1
t

False

In [163]:
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]
u

True

In [164]:
valor3 = p or q or r or s or t or u
valor3

True

In [165]:
valor4 = not (p or q or r or s or t or u)
valor4

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [166]:
import pandas as pd

In [167]:
df_novo7 = pd.read_csv("arquivoaula7.csv", index_col="Unnamed: 0")
df_novo7 = df_novo7.round(3)
df_novo7

,a,b,c,d,media_linhas
amarelo,2.600,2.800,34.729,0.069,10.050
azul,0.139,1.612,1.673,5.893,2.329
vermelho,0.263,0.372,2.600,2.800,1.509
roxo,34.729,0.069,0.139,1.612,9.137
verde,1.673,5.893,0.263,0.372,2.050
media_colunas,7.881,2.149,7.881,2.149,5.015


In [168]:
linha2 = df_novo7.iloc[1]
linha3 = df_novo7.iloc[2]
linha4 = df_novo7.iloc[3]

resultado = (linha2 == linha3).all() or (linha3 == linha4).all()
print(resultado)


False


## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [169]:
linha1 = df_novo7.iloc[0]
maior_ou_igual = (linha1 >= 10).all()
print(maior_ou_igual)

False


In [170]:
print(linha1)

a                2.600
b                2.800
c               34.729
d                0.069
media_linhas    10.050
Name: amarelo, dtype: float64


## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [171]:
##Todos = .all()
coluna3 = df_novo7.iloc[:, 2]
resultado = ((coluna3 >= 0) & (coluna3 <= 40)).all()
print(resultado)

True


In [172]:
print(coluna3)

amarelo          34.729
azul              1.673
vermelho          2.600
roxo              0.139
verde             0.263
media_colunas     7.881
Name: c, dtype: float64


## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [173]:
## Algum: .any()
ultima_linha = df_novo7.iloc[-1]
acima_10 = (ultima_linha > 10).any()
print(acima_10)

False


In [174]:
print(ultima_linha)

a               7.881
b               2.149
c               7.881
d               2.149
media_linhas    5.015
Name: media_colunas, dtype: float64


## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [175]:
### and = &
acima5 = df_novo7[(df_novo7 > 5) & (df_novo7 < 7)]
print(acima5)

                a      b   c      d  media_linhas
amarelo       NaN    NaN NaN    NaN           NaN
azul          NaN    NaN NaN  5.893           NaN
vermelho      NaN    NaN NaN    NaN           NaN
roxo          NaN    NaN NaN    NaN           NaN
verde         NaN  5.893 NaN    NaN           NaN
media_colunas NaN    NaN NaN    NaN         5.015


In [176]:
print(df_novo7)

                    a      b       c      d  media_linhas
amarelo         2.600  2.800  34.729  0.069        10.050
azul            0.139  1.612   1.673  5.893         2.329
vermelho        0.263  0.372   2.600  2.800         1.509
roxo           34.729  0.069   0.139  1.612         9.137
verde           1.673  5.893   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149         5.015


## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [177]:
# or = |
abaixo5 = df_novo7[(df_novo7 <= 5) | (df_novo7 > 7)]
print(abaixo5)

                    a      b       c      d  media_linhas
amarelo         2.600  2.800  34.729  0.069        10.050
azul            0.139  1.612   1.673    NaN         2.329
vermelho        0.263  0.372   2.600  2.800         1.509
roxo           34.729  0.069   0.139  1.612         9.137
verde           1.673    NaN   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149           NaN


## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [178]:
##Convertendo Df em array
array1 = df_novo7.iloc[:, -2].to_numpy()
array2 = df_novo7.iloc[:, -1].to_numpy()
print(array1)
print(array2)

[0.069 5.893 2.8   1.612 0.372 2.149]
[10.05   2.329  1.509  9.137  2.05   5.015]


In [179]:
#Primeiro array
entre2_5_a1 = ((array1 >= 2) & (array1 <= 5)).any()
print(entre2_5_a1)

True


In [180]:
##Segundo array
entre2_5_a2 = ((array2 >= 2) & (array2 <= 5)).any()
print(entre2_5_a2)

True


In [181]:
## Juntando as duas ultimas colunas
array3 = [array1] + [array2]
array3

[array([0.069, 5.893, 2.8  , 1.612, 0.372, 2.149]),
 array([10.05 ,  2.329,  1.509,  9.137,  2.05 ,  5.015])]

In [182]:
## Descobrindo quais são os valores contidos >=2 & <=5
import numpy as np
array3 = np.array(array3)
resultado = array3[(array3 >= 2) & (array3 <= 5)]
print(resultado)

[2.8   2.149 2.329 2.05 ]


## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [183]:
supe_1_inf12 = ((array1 > -1) & (array1 < 12)).all() and ((array2 > -1) & (array2 < 12)).all()
print(supe_1_inf12)

True


In [184]:
## Mostrando quais são os valores maiores que -1 e menores que 12
resultado = array3[(array3 > -1) & (array3 <12)]
print(resultado)

[ 0.069  5.893  2.8    1.612  0.372  2.149 10.05   2.329  1.509  9.137
  2.05   5.015]
