In [ ]:
"Py" == "Py"

True

In [2]:
"Py" != "Py"

False

In [5]:
1 == True

True

In [6]:
"1" == True

False

In [7]:
1 == True

True

In [8]:
1.0 == False

False

In [9]:
0 == False

True

In [10]:
"0" == False

False

In [11]:
2 >= 2.0

True

In [13]:
2 >= 2.01

False

In [14]:
2 <= 2.01

True

In [15]:
2 <= 3 < 4 

True

In [16]:
4 <= 7 < 4 

False

In [17]:
import numpy as np
import pandas as pd

In [ ]:
(1, 2) == (1.0, 2.0)


True

In [20]:
(1, 2) == (1.0, 2.1)

False

In [19]:
(1, 2) == [1.0, 2.0]

False

In [21]:
(1, 2) == (1.0, 2.0, 1)

False

In [22]:
(1, 2) <= (1.0, 2.0, 1)

True

In [26]:
(1, 2) == (1.0, 2.0, 1)

False

In [37]:
lista_3 = [1, 2, 3]
lista_2 = [1, 2, 3]
lista_3 == lista_2

True

In [41]:
{'a': 1}.values() == {'a': 1}.values() 

False

In [42]:
'a' <= 'b'

True

In [47]:
## media, dp, número de elementos
np.random.normal(0, 1, 10)

array([-0.06711123, -0.09161925,  0.0139321 ,  0.40006977,  0.31069423,
       -0.14323926,  0.39959326,  0.65571501,  1.9944295 ,  1.32928356])

In [48]:
np.random.normal(0, 1, 1_000).reshape(10, -1)

array([[-7.63188656e-01,  1.39384575e-01, -3.14643405e-01,
         1.69010504e+00,  3.90595728e-01, -1.63574975e-02,
        -1.12073617e-01, -1.69800065e-01, -5.41265360e-01,
        -6.93930687e-01, -1.25435612e+00,  1.13949772e+00,
         7.93626078e-01,  1.14639135e-01,  6.24169194e-01,
        -1.42076131e-01,  2.95752555e-01, -5.80116575e-01,
         1.01530975e+00,  5.04249196e-01,  8.90009627e-01,
        -1.79402974e-01, -1.27862326e+00,  3.59107141e-01,
         2.67105706e+00,  1.32874250e-01,  1.40077745e+00,
        -2.59198852e-01, -8.68850624e-01,  1.29189488e+00,
         1.54677700e+00, -1.94292326e-01, -5.68840335e-01,
         1.17918595e+00, -5.17440708e-01,  1.95510430e+00,
         9.59183366e-02,  5.00306327e-01, -1.05310680e-02,
         1.43760423e-01,  8.08499766e-01, -1.60918101e+00,
         3.36614569e-01,  1.37667670e+00, -9.22992420e-01,
        -1.73817610e+00,  5.62640876e-01, -1.26679781e+00,
         4.66116194e-01, -1.32710969e+00, -2.11804527e+0

In [51]:
array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array [:2]

array([[-0.42387928,  0.3172505 ,  2.06625609,  0.49086854,  0.27687927,
        -0.42696953, -0.05804336,  1.68216674, -0.39410915, -0.09313091],
       [-0.95677699,  1.83266522,  0.615069  ,  1.16651284,  0.04688873,
         0.60683651, -0.46624915, -0.15882596, -0.34413607,  1.16225009]])

In [52]:
array_1 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array_2 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array_1 [:2]

array([[-1.64172635, -0.45343257,  1.75127913, -0.96607899,  1.87384942,
        -0.23271443, -1.13136501,  0.35783934,  1.6125271 ,  1.01007235],
       [-0.5464784 , -0.64398716,  0.26280161, -2.16999515,  0.45679299,
         0.33617127,  0.85666591,  0.48383136, -0.20447714, -1.27661436]])

In [53]:
array_1 == array_2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

In [58]:
## conjunto de dados aleatórios iguais
np.random.seed(42)
array_1 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array_2 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
print(array_1[:1])
print(array_2[:1])

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
   1.57921282  0.76743473 -0.46947439  0.54256004]]
[[ 1.39935544  0.92463368  0.05963037 -0.64693678  0.69822331  0.39348539
   0.89519322  0.6351718   1.04955272 -0.53523521]]


In [57]:
array_1 == array_2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

In [59]:
pd.DataFrame(array_1) <= pd.DataFrame(array_2)

,0,1,2,3,4,5,6,7,8,9
0,True,True,False,False,True,True,False,False,True,False
1,True,True,True,True,True,True,True,False,True,True
2,False,False,False,True,True,True,True,False,True,False
3,True,False,True,True,False,True,False,True,True,True
4,True,False,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...
95,False,True,True,False,False,True,False,True,True,False
96,False,False,True,False,True,False,True,False,False,True
97,True,False,False,True,True,True,True,True,True,False
98,False,False,True,True,True,True,False,False,False,True


In [60]:
filtro_array = array_1 <= array_2
filtro_array[:2]

array([[ True,  True, False, False,  True,  True, False, False,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True]])

In [61]:
df_1 = pd.DataFrame(array_1)
df_2 = pd.DataFrame(array_2)
df_1.head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040


In [62]:
df_1[filtro_array].head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
